[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "MISIS_labs"
version = "25.11.2025"
description = "Лабораторные работы по дисциплине 'Программирование и алгоритмизация'"
author = [
    {GitHub: "wasted011"}
]

[project.dependencies]
dev = [
    "click>=8.3.1",
    "pytokens>=0.3.0",
    "Pygments>=2.19.2",
    "pathspec>=0.12.1",
    "platformdirs>=4.0.0",
    "packaging>=25.0",
    "pip>=25.3"
]

excel = [
    "openpyxl>=3.1.5",
    "et_xmlfile>=2.0.0",
]

tests = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "coverage>=7.12.0",
    "pluggy>=1.6.0",
    "iniconfig>=2.3.0"
]

black = [
    "black>=25.11.0"
]


[pytest]
test_paths = ["tests"]
python_test_files = ["test_***.py"]
python_test_functions = ["test_***"]
addopts = [
    "-v",
    "--cov"
]
